version: '3'

services:
    frontend:
        container_name: frontend
        build:
            context: .
        # command: yarn run dev
        # 下記から修正 動かなくなるかも
        command: bash -c "yarn run dev"
        # command: bash -c " yarn install && yarn run dev"
        volumes:
            - .:/app
        ports:
            - 8080:3000
            # - 3000:3000
        tty: true
        environment:
            NODE_OPTIONS: --openssl-legacy-provider
