version: '3'

services:
    frontend:
        container_name: frontend
        build:
            context: .
        # command: yarn run dev
        command: bash -c " yarn install && yarn run dev"
        volumes:
            - .:/app
        ports:
            - 3000:3000
        tty: true
        environment: 
            NODE_OPTIONS: --openssl-legacy-provider
