FROM node:18.12.1-alpine
# FROM node:18.12.1

ARG HOMEDIR="app"

ENV HOME=/$HOMEDIR \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    # コンテナのnuxt.jsをブラウザから参照するため
    HOST=0.0.0.0 \
    # OpenSSLの互換エラー対応
    NODE_OPTIONS=--openssl-legacy-provider

# RUN echo $HOMEDIR
# RUN echo $CONTAINER_PORT

WORKDIR $HOMEDIR

# COPY ./ ./
COPY package.json .
COPY . .

RUN apk update && apk add bash

RUN yarn install
RUN yarn run build

# EXPOSE 3000
EXPOSE 8080

CMD ["yarn", "start"]
