version: '3'

services:
    db:
        image: mysql:8.0.31
        environment: 
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=pass
            - TZ=Asia/Tokyo
        ports: 
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - mysql-data:/var/lib/mysql

    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3020 -b '0.0.0.0'"
        volumes: 
            - .:/app:cached
            - public:/app/public
            - tmp:/app/tmp
        stdin_open: true
        tty: true
        environment: 
            # DB_ROOT_USERNAME: root
            # DB_USERNAME: user
            # DB_PASSWORD: password
            TZ: Asia/Tokyo
            # DB_HOST: db
            # RAILS_ENV: development
        depends_on: 
            - db
        ports:
            - "3000:3000"

volumes:
    mysql-data:
    tmp:
    public:
