version: '3'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/app:cached
            - public:/app/public
            - tmp:/app/tmp
        stdin_open: true
        tty: true
        environment: 
            MYSQL_ROOT_PASSWORD: password
            DB_HOST: db
            TZ: Asia/Tokyo
            # RAILS_ENV: development
            # DB_USERNAME: user
            # DB_PASSWORD: password
        depends_on: 
            - db
        ports:
            - "3000:3000"

    db:
        container_name: db
        image: mysql:8.0.31
        environment: 
            MYSQL_ROOT_PASSWORD: password
            TZ: Asia/Tokyo
            # MYSQL_DATABASE: app_development
            # MYSQL_USER: user
            # MYSQL_PASSWORD: password
        ports: 
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - mysql-data:/var/lib/mysql
        

volumes:
    mysql-data:
    tmp:
    public:
