# version: '3'
version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server"
        volumes:
            - .:/app:cached
            - public:/app/public
            - tmp:/app/tmp
        stdin_open: true
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            TZ: Asia/Tokyo
            BASE_URL: "http://localhost:3000"
            # DB_HOST: "db"
            # RAILS_ENV: development
            # DB_USERNAME: user
            # DB_PASSWORD: password
        ports:
            - "3000:3000"
        depends_on:
            - db

    # nginx
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.prod
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - public:/portfolio01-app/public
            - tmp:/portfolio01-app/tmp
        ports:
            - "80:80"
        depends_on:
            - web

volumes:
    mysql-data:
    tmp:
    public:
