version: '3'

services:
    
    web:
        build: 
            context: .
            dockerfile: ./docker/web/Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3020 -b '0.0.0.0'"
        volumes: 
            - .:/app:cached
            - public:/app/public
            - tmp:/app/tmp
        stdin_open: true
        tty: true
        # environment: 
        #     DB_ROOT_USERNAME: root
        #     DB_USERNAME: user
        #     DB_PASSWORD: password
        #     TZ: Asia/Tokyo
        #     DB_HOST: db
        #     RAILS_ENV: development
        ports:
            - "3000:3000"
        

volumes:
    mysql-data:
    tmp:
    public:
