source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# dotenv
gem 'dotenv-rails'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# add
# モデルに現在のDB構造をメモする機能
gem 'annotate'

# add
# jwt
gem 'jwt', '~> 2.7'

# add
# コンソールの出力結果を見やすく表示する (日本語翻訳用gemも)
gem 'hirb', '~> 0.7.3'
gem 'hirb-unicode-steakknife', '~> 0.0.9'

# add
# 画像を管理
gem 'carrierwave', '~> 2.2', '>= 2.2.3'
# gem 'fog-aws', '~> 0.7.6'
# gem 'mime-types'
gem 'mime-types'
gem 'fog-aws'

# xss対策 doc: https://github.com/rgrove/sanitize
gem 'sanitize'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

  # add
  # デバッグツール
  gem 'pry-byebug'

  # lintツール(文法チェックツール)
  # 確認は右記 => bundle exec rubocop
  # 全て修正は右記 => bundle exec rubocop -a
  # gem 'rubocop-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false

  # rspec
  # bundle exec rspec
  gem 'rspec-rails'
  gem 'factory_bot_rails'

  # add
  # faker
  gem 'faker', '~> 3.1', '>= 3.1.1'

end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # add
  # testに色付けする
  gem 'minitest-reporters', '~> 1.5'
end

