
version: 2.1

orbs:
    ruby: circleci/ruby@1.4.0
    node: circleci/node@5.0.3
    aws-ecr: circleci/aws-ecr@8.2.1

jobs:
    build:
        machine:
            image: ubuntu-2004:2022.10.1
        steps:
            - checkout
            - run:
                name: backend build
                command: docker-compose -f ./backend/docker-compose.yml build
            - run:
                name: frontend build
                command: docker-compose -f ./frontend/docker-compose.yml build

    test:
        machine:
            image: ubuntu-2004:2022.10.1
        steps:
            - checkout
            - run:
                name: backend container
                command: docker-compose -f ./backend/docker-compose.yml up -d
            - run:
                name: frontend container
                command: docker-compose -f ./frontend/docker-compose.yml up -d
            - run: sleep 20

            # backend test
            - run:
                name: backend db create
                command: docker-compose -f ./backend/docker-compose.yml run web rails db:create RAILS_ENV=test
            - run:
                name: backend db migrate
                command: docker-compose -f ./backend/docker-compose.yml run web rails db:migrate RAILS_ENV=test
            - run:
                name: backend test
                command: docker-compose -f ./backend/docker-compose.yml run web bundle exec rspec

            # frontend test
            - run:
                name: frontend yarn install
                command: docker-compose -f ./frontend/docker-compose.yml run frontend yarn install
            - run:
                name: frontend test
                command: docker-compose -f ./frontend/docker-compose.yml run frontend yarn test

            # down
            - run:
                name: frontend down
                command: docker-compose -f ./frontend/docker-compose.yml down
            - run:
                name: backend down
                command: docker-compose -f ./backend/docker-compose.yml down

    build_and_push_image_backend_nginx:
        machine:
            image: ubuntu-2004:2022.10.1
            steps:
                - checkout
                - aws-ecr/build-and-push-image:
                    account-url: AWS_ACCOUNT_URL
                    repo: 'bestpra/backend-nginx'
                    region: AWS_REGION
                    tag: "${CIRCLE_SHA1}"
                    path: '../backend/docker/nginx'
                    dockerfile: Dockerfile.prod

    build_and_push_image_backend_rails:
        machine:
            images: ubuntu-2004:2022.10.1
            steps:
                - checkout
                - aws-ecr/build-and-push-image:
                    account-url: AWS_ACCOUNT_URL
                    repo: 'bestpra/backend-rails'
                    region: AWS_REGION
                    tag: "${CIRCLE_SHA1}"
                    path: '../backend//docker/web'
                    dockerfile: Dockerfile.prod

    build_and_push_image_frontend:
        machine:
            images: ubuntu-2004:2022.10.1
            steps:
                - checkout
                - aws-ecr/build-and-push-image:
                    account-url: AWS_ACCOUNT_URL
                    repo: 'bestpra/frontend'
                    region: AWS_REGION
                    tag: "${CIRCLE_SHA1}"
                    path: '../frontend/'
                    dockerfile: Dockerfile.prod

# 順序を整理
workflows:
    build_test_deploy:
        jobs:
            - build
            - test:
                requires:
                    - build
            - build_and_push_image_backend_nginx:
                requires:
                    - test
                filters:
                    branches:
                        only: main
            - build_and_push_image_backend_rails:
                requires:
                    - test
                filters:
                    branches:
                        only: main
            - build_and_push_image_frontend:
                requires:
                    - test
                filters:
                    branches:
                        only: main